
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Oct 14 23:35:03 CST 2020
//----------------------------------------------------

package proyectofinal.ctdoa.backend.analizador.java;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MAS_MAS = 40;
  public static final int CONSOLA = 4;
  public static final int NUMERO = 52;
  public static final int POR = 12;
  public static final int CHAR = 9;
  public static final int CASE = 36;
  public static final int DIFERENTE = 18;
  public static final int MENOS_MENOS = 41;
  public static final int DOS_PUNTOS = 16;
  public static final int CORCHETE_C = 45;
  public static final int INT = 7;
  public static final int CORCHETE_A = 44;
  public static final int FOR = 29;
  public static final int FINPUT = 49;
  public static final int AND = 24;
  public static final int NOT = 23;
  public static final int IGUAL = 15;
  public static final int CARACTER = 3;
  public static final int OR = 25;
  public static final int CLASS = 39;
  public static final int DIV = 13;
  public static final int ELSE_IF = 31;
  public static final int IF = 30;
  public static final int THIS = 5;
  public static final int ID = 54;
  public static final int PUNTO_COMA = 42;
  public static final int IGUAL_IGUAL = 17;
  public static final int EOF = 0;
  public static final int RETURN = 35;
  public static final int error = 1;
  public static final int COMA = 43;
  public static final int CADENA = 2;
  public static final int CONSOLA_LINEA = 51;
  public static final int MENOS = 11;
  public static final int MENOR = 19;
  public static final int MOD = 14;
  public static final int BREAK = 28;
  public static final int VOID = 38;
  public static final int SWITCH = 33;
  public static final int REAL = 53;
  public static final int MAYOR = 20;
  public static final int CINPUT = 50;
  public static final int ELSE = 32;
  public static final int PUNTO = 6;
  public static final int PARENTESIS_C = 47;
  public static final int WHILE = 26;
  public static final int PARENTESIS_A = 46;
  public static final int DEFAULT = 34;
  public static final int MAYOR_IGUAL = 22;
  public static final int PUBLIC = 37;
  public static final int FLOAT = 8;
  public static final int IINPUT = 48;
  public static final int MENOR_IGUAL = 21;
  public static final int DO = 27;
  public static final int MAS = 10;
}

