
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Oct 14 23:35:03 CST 2020
//----------------------------------------------------

package proyectofinal.ctdoa.backend.analizador.c;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMILLAS = 58;
  public static final int REAL = 70;
  public static final int MENOR_IGUAL = 34;
  public static final int SCANF = 39;
  public static final int CONST = 46;
  public static final int COD_VB = 3;
  public static final int MAYOR = 33;
  public static final int DIFERENTE = 31;
  public static final int LEER_FLOAT = 42;
  public static final int POR = 22;
  public static final int NUMERO = 69;
  public static final int IGUAL_IGUAL = 30;
  public static final int NOT = 36;
  public static final int COMENTARIO = 2;
  public static final int CORCHETE_C = 66;
  public static final int CORCHETE_A = 65;
  public static final int ERROR = 72;
  public static final int FLOAT = 18;
  public static final int DOS_PUNTOS = 62;
  public static final int LLAVE_C = 64;
  public static final int LLAVE_A = 63;
  public static final int PUNTO_COMA = 61;
  public static final int MOD = 24;
  public static final int INCLUDE = 7;
  public static final int COMA = 60;
  public static final int LIBRERIA_PYTHON = 10;
  public static final int CLRSCR = 28;
  public static final int PRINTF = 57;
  public static final int IGUAL = 27;
  public static final int WHILE = 55;
  public static final int CHAR = 19;
  public static final int ELSE_IF = 48;
  public static final int GETCH = 6;
  public static final int LEER_INT = 40;
  public static final int SWITCH = 50;
  public static final int COD_JAVA = 5;
  public static final int DO = 56;
  public static final int PY = 15;
  public static final int FOR = 54;
  public static final int VOID = 44;
  public static final int DIV = 23;
  public static final int ELSE = 49;
  public static final int MENOS = 21;
  public static final int MENOR = 32;
  public static final int MAS = 20;
  public static final int BREAK = 53;
  public static final int LIBRERIA_CLASES = 8;
  public static final int JAVA = 16;
  public static final int AMPERSAND = 29;
  public static final int INT = 17;
  public static final int PARENTESIS_C = 68;
  public static final int PARENTESIS_A = 67;
  public static final int EOF = 0;
  public static final int PUNTO = 59;
  public static final int DEFAULT = 52;
  public static final int CARACTER = 13;
  public static final int VB = 14;
  public static final int MAIN = 45;
  public static final int OR = 38;
  public static final int error = 1;
  public static final int IF = 47;
  public static final int LIBRERIA_JAVA = 9;
  public static final int ID = 71;
  public static final int CASE = 51;
  public static final int MAS_MAS = 25;
  public static final int MENOS_MENOS = 26;
  public static final int LEER_CHAR = 41;
  public static final int AND = 37;
  public static final int LIBRERIA_VB = 11;
  public static final int LIBRERIA_C = 12;
  public static final int PROGRAMA = 43;
  public static final int COD_PY = 4;
  public static final int MAYOR_IGUAL = 35;
}

