
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Oct 14 23:35:03 CST 2020
//----------------------------------------------------

package proyectofinal.ctdoa.backend.analizador.python;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int REAL = 41;
  public static final int MENOR_IGUAL = 15;
  public static final int CINPUT = 37;
  public static final int MAYOR = 14;
  public static final int INDENT = 38;
  public static final int DIFERENTE = 12;
  public static final int DEDENT = 39;
  public static final int ELIF = 27;
  public static final int POR = 6;
  public static final int NUMERO = 40;
  public static final int DISTINTO = 10;
  public static final int IGUAL_IGUAL = 11;
  public static final int NOT = 17;
  public static final int DEF = 28;
  public static final int DOS_PUNTOS = 31;
  public static final int MOD = 8;
  public static final int COMA = 30;
  public static final int IGUAL = 9;
  public static final int WHILE = 21;
  public static final int FINPUT = 36;
  public static final int FOR = 22;
  public static final int DIV = 7;
  public static final int RETURN = 29;
  public static final int ELSE = 26;
  public static final int MENOS = 5;
  public static final int MENOR = 13;
  public static final int MAS = 4;
  public static final int SALTO = 34;
  public static final int PARENTESIS_C = 33;
  public static final int PARENTESIS_A = 32;
  public static final int EOF = 0;
  public static final int PRINT = 20;
  public static final int CARACTER = 3;
  public static final int IN = 23;
  public static final int OR = 19;
  public static final int error = 1;
  public static final int IF = 25;
  public static final int ID = 42;
  public static final int IINPUT = 35;
  public static final int CADENA = 2;
  public static final int RANGE = 24;
  public static final int AND = 18;
  public static final int MAYOR_IGUAL = 16;
}

